import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Target, ShieldCheck, CheckCircle2, Info, ChevronRight, BarChart2 } from 'lucide-react';
import { PrototypeBadge } from '../components/PrototypeBadge';
import { FIXTURE_TARGETS } from '../services/fixtures';

export const TargetAnalysis: React.FC = () => {
  const { targetId } = useParams<{ targetId: string }>();
  const target = FIXTURE_TARGETS.find((t) => t.target_id === targetId) || FIXTURE_TARGETS[0];

  return (
    <div className="w-full max-w-7xl mx-auto px-4 md:px-8 py-6 space-y-6">
      <PrototypeBadge type="banner" />

      {/* Back to Targets Link */}
      <Link to="/drill-planning" className="inline-flex items-center gap-1.5 text-xs font-bold text-[#1E3A8A] hover:underline">
        <ArrowLeft className="w-4 h-4" />
        <span>Return to Drill Target Queue</span>
      </Link>

      {/* Page Title Header */}
      <div className="bg-white border-l-4 border-[#D4AF37] border border-slate-200 p-6 rounded shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-bold text-[#1E3A8A] uppercase tracking-wider">
            <Target className="w-4 h-4 text-amber-500" />
            <span>SHAP MODEL ATTRITION BREAKDOWN</span>
          </div>
          <h1 className="text-2xl font-bold text-[#0B192C] font-serif mt-1">
            Target Analysis: {target.target_id}
          </h1>
          <p className="text-xs text-slate-600 mt-1">
            Model-attributed feature contributions generated by tree SHAP explainer on validated spatial grid.
          </p>
        </div>
        <div className="bg-[#0B192C] text-white p-3 rounded text-xs font-mono border-l-2 border-amber-400">
          <p className="text-amber-400 font-bold">Prospectivity Score</p>
          <p className="text-xl font-extrabold text-white">{(target.mean_prospectivity * 100).toFixed(1)}%</p>
        </div>
      </div>

      {/* SHAP Feature Contribution Table & Chart */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 bg-white rounded border border-slate-200 p-6 shadow-sm space-y-4">
          <h3 className="text-base font-bold text-[#0B192C] font-serif border-b border-slate-200 pb-3 flex items-center justify-between">
            <span>Model-Attributed Feature Contributions</span>
            <span className="text-xs font-normal text-slate-500">Tree SHAP Values (Random Forest Model)</span>
          </h3>

          <div className="space-y-3">
            {(target.shap_summary || []).map((shap, idx) => (
              <div key={idx} className="p-3 bg-slate-50 border border-slate-200 rounded space-y-1.5 text-xs">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-[#0B192C]">{shap.feature}</span>
                  <span className={`font-bold ${shap.direction === 'positive' ? 'text-emerald-700' : 'text-red-700'}`}>
                    {shap.contribution > 0 ? '+' : ''}{shap.contribution.toFixed(2)} SHAP
                  </span>
                </div>
                <div className="w-full bg-slate-200 rounded-full h-2 overflow-hidden">
                  <div 
                    className={`h-full rounded-full ${shap.direction === 'positive' ? 'bg-[#1E3A8A]' : 'bg-red-500'}`} 
                    style={{ width: `${Math.min(100, Math.abs(shap.contribution) * 400)}%` }} 
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Right Info Box */}
        <div className="bg-white rounded border border-slate-200 p-6 shadow-sm space-y-4 text-xs">
          <h3 className="text-base font-bold text-[#0B192C] font-serif border-b border-slate-200 pb-3">
            Geological & Structural Summary
          </h3>
          <div className="space-y-3 text-slate-700 leading-relaxed">
            <p>
              <strong>Geological Support:</strong> {target.geological_support}
            </p>
            <p>
              <strong>Structural Support:</strong> {target.structural_support}
            </p>
            <p>
              <strong>Data Completeness:</strong> {target.data_completeness}%
            </p>
            <p>
              <strong>Recommended Action:</strong> {target.recommended_action}
            </p>
          </div>
          <div className="p-3 bg-amber-50 rounded border border-amber-200 text-amber-900 text-[11px]">
            ⚠ Model attribution does not equal causality. Field mapping remains required.
          </div>
        </div>
      </div>
    </div>
  );
};
